### ISSUE TITLE
033 and identi.ca

### ISSUE THREAD

**Issue by gregoa** [gregkh/bti#29]
The changes in 033 for the Twitter API v1.1 are not good for identi.ca. Posting still works (if one ignores the "operation failed" message with exit code 234). Retrieving with -'-action friends --debug' shows returned JSON but no output and again "operation failed"/234).

OTOH I don't know if it's worth to investigate since identi.ca is supposed to switch to pump.io Any Day Now (since 4 weeks). Not sure about other statusnet instances ...

**Comment by kaimi** [comment]
> Right, it would only help for other StatusNet instances but there are
probably not many around.

Well yes, there are :)

I only use bti for posting though, so at least for me, the current state is fine.
