### ISSUE TITLE
oauth_split_url_parameters returns 5

### ISSUE THREAD

**Issue by arssivka** [gregkh/bti#39]
I can't login using oauth. I created config file with consumer's keys from README file.
Program requested me to enter PIN from url which was printed at line above. After entering pin program do nothing. Debugging step-by-step showed me where program has incorrect behavior. In my case function oauth_split_url_parameters writes into rc value 5 in function parse_osp_reply (line 740), but case for 5 don't exists and program exits, but I had correct responce.

**Comment by gregkh** [comment]
Ick.  Care to make up a patch?

**Comment by arssivka** [comment]
No problem. I've created pull request.

**Comment by gregkh** [comment]
Thanks for this, should now be resolved.

**Comment by Jacobtey** [comment]
Hi! What about a new release including this patch to enable distributions to change its packages?
